### PR TITLE
Update Mahjongg to 3.40.1

### PR DESCRIPTION
**Pull request by mathiascode**
~~With a few patches from main to make it playable, until a new release is available.~~

Replaces https://github.com/flathub/org.gnome.Mahjongg/pull/17

### CODE REVIEW

**Comment by mathiascode** [comment]
bot, build

**Comment by sukahiroaki** [comment]
GNOME 44 runtime is going to be marked as EOL pretty soon now, so any chance of getting this merged (maybe even with a bump to the GNOME 46 runtime? Also right now the latest release is only available via Gnome Nightly not Flathub, which is a shame.

**Comment by mathiascode** [comment]
Bumped to GNOME 46 runtime in case someone wants to merge this, but I'm not sure if the package has an active maintainer anymore. Perhaps @bilelmoussaoui?

**Comment by mathiascode** [comment]
I'm working on getting a new upstream release out that includes these patches. Until then, I'll only bump the runtime version.

**Pull request merged**
